apiVersion: v1
kind: Secret
metadata:
  name: visioncount-app-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg2://visioncount:visioncount@postgres:5432/visioncount
  ULTRALYTICS_HUB_API_KEY: ""
  NOGROK_AUTHTOKEN: ""
  MINIO_ACCESS_KEY: visioncount
  MINIO_SECRET_KEY: visioncount123
