apiVersion: v1
kind: Secret
metadata:
  name: visioncount-app-secrets
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:replace_me,iv:replace_me,tag:replace_me,type:str]
  ULTRALYTICS_HUB_API_KEY: ENC[AES256_GCM,data:replace_me,iv:replace_me,tag:replace_me,type:str]
  NOGROK_AUTHTOKEN: ENC[AES256_GCM,data:replace_me,iv:replace_me,tag:replace_me,type:str]
  MINIO_ACCESS_KEY: ENC[AES256_GCM,data:replace_me,iv:replace_me,tag:replace_me,type:str]
  MINIO_SECRET_KEY: ENC[AES256_GCM,data:replace_me,iv:replace_me,tag:replace_me,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "1970-01-01T00:00:00Z"
  mac: ENC[AES256_GCM,data:replace_me,iv:replace_me,tag:replace_me,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
