apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - hpa-backend.yaml
  - pdb.yaml
configMapGenerator:
  - name: visioncount-app-config
    behavior: merge
    envs:
      - app-config.env
patches:
  - path: patch-backend-prod.yaml
  - path: patch-frontend-prod.yaml
  - path: patch-redpanda-prod.yaml
