apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: visioncount-backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: visioncount-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: visioncount-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: visioncount-frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redpanda
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redpanda
